pipeline {
    agent { docker { image 'maven:3.3.3' } }
    stages {
        stage('build') {
            steps {
                sh 'mvn clean build'
            }
        }
        stage('Deploy') {
            steps {
            	sh 'docker-compose build'
            	sh 'docker-compose down'
            	sh 'docker-compose up'
            }
        }
      }
}