pipeline {
    agent { docker { image 'maven:3.3.3' } }
    stages {
        stage('build') {
            steps {
                sh 'mvn clean build'
            }
        }
        stage('Deploy') {
            steps {
            	sh 'docker-compose build'
            	sh 'docker-compose down'
            	sh 'docker compose up'
            }
        }
        
        post {
	        always {
	            echo 'One way or another, I have finished'
	            deleteDir() /* clean up our workspace */
	        }
	        success {
	            echo 'I succeeeded!'
	        }
	        unstable {
	            echo 'I am unstable :/'
	        }
	        failure {
	            echo 'I failed :('
	        }
	        changed {
	            echo 'Things were different before...'
	        }
    	}
        
    }
}